apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkmate-backend
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.slack: "info-deploy"
spec:
  project: default
  source:
    repoURL: "https://github.com/Starmix-ajou/checkmate-manifest"
    targetRevision: main
    path: apps/backend
  destination:
    server: "https://kubernetes.default.svc"
    namespace: checkmate-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
