apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-backend
  namespace: checkmate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmate-backend
  template:
    metadata:
      labels:
        app: checkmate-backend
    spec:
      containers:
        - name: checkmate-backend
          image: yny.ocir.io/ax1nm9kw34v6/checkmate:25ca5e64b06808dca80e6fcef6f866d4c8a328a2
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: checkmate-backend-secret
      imagePullSecrets:
        - name: ocir-secret
