apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-backend
  namespace: checkmate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmate-backend
  template:
    metadata:
      labels:
        app: checkmate-backend
    spec:
      containers:
        - name: checkmate-backend
          image: yny.ocir.io/ax1nm9kw34v6/checkmate:3312e2d2dd0339b0b3b47d0f1c8c59daf6eb3767
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: checkmate-backend-secret
      imagePullSecrets:
        - name: ocir-secret
