apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Starmix-ajou/checkmate-manifest"
    targetRevision: main
    path: deploy/runner
  destination:
    server: "https://kubernetes.default.svc"
    namespace: actions-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true