apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: checkmate-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: Starmix-ajou/checkmate-backend
      labels:
        - k8s