apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: checkmate-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Starmix-ajou/checkmate-backend"
    targetRevision: main
    path: deploy
  destination:
    server: "https://kubernetes.default.svc"
    namespace: checkmate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true