apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: checkmate-runner
  namespace: actions-runner
spec:
  replicas: 1
  template:
    spec:
      organization: Starmix-ajou 
      labels:
        - "self-hosted"
        - "checkmate"
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: actions-token
              key: github_token