apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmate-ai
  namespace: checkmate-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkmate-ai
  template:
    metadata:
      labels:
        app: checkmate-ai
    spec:
      containers:
        - name: checkmate-ai
          image: yny.ocir.io/ax1nm9kw34v6/checkmate-ai:68ee4c3dfbf9e0e3de49155543c8687d209299e5
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: checkmate-ai-secret
      imagePullSecrets:
        - name: ocir-secret
