apiVersion: v1
kind: Service
metadata:
  name: checkmate-ai-svc
  namespace: checkmate-ai
spec:
  selector:
    app: checkmate-ai
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
